export enum ACTIONS {
    ACTION_COMPETITION_FETCH_SINGLE_STARTED = 'competition/FETCH_SINGLE_STARTED',
    ACTION_COMPETITION_FETCH_SINGLE_FAILED = 'competition/FETCH_SINGLE_FAILED',
    ACTION_COMPETITION_FETCH_SINGLE_COMPLETED = 'competition/FETCH_SINGLE_COMPLETED',
    ACTION_COMPETITION_FETCH_ALL_STARTED = 'competition/FETCH_ALL_STARTED',
    ACTION_COMPETITION_FETCH_ALL_FAILED = 'competition/FETCH_ALL_FAILED',
    ACTION_COMPETITION_FETCH_ALL_COMPLETED = 'competition/FETCH_ALL_COMPLETED'
}